// Generated by scripts/generate-sounds.cjs.
(function(root) {
  const manifest = {
  "version": "20260906-a",
  "sampleRate": 44100,
  "sounds": {
    "dartThrow": {
      "files": [
        "dartThrow.wav",
        "dartThrow-2.wav",
        "dartThrow-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "nailThrow": {
      "files": [
        "nailThrow.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "machineBox": {
      "files": [
        "machineBox.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "silkArmor": {
      "files": [
        "silkArmor.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "needleRain": {
      "files": [
        "needleRain.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "dartImpact": {
      "files": [
        "dartImpact.wav",
        "dartImpact-2.wav",
        "dartImpact-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "swordSwing": {
      "files": [
        "swordSwing.wav",
        "swordSwing-2.wav",
        "swordSwing-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "swordImpact": {
      "files": [
        "swordImpact.wav",
        "swordImpact-2.wav",
        "swordImpact-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "swordBeam": {
      "files": [
        "swordBeam.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "crossCut": {
      "files": [
        "crossCut.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "thrust": {
      "files": [
        "thrust.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "counterStance": {
      "files": [
        "counterStance.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "counterHit": {
      "files": [
        "counterHit.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "boxerDash": {
      "files": [
        "boxerDash.wav",
        "boxerDash-2.wav",
        "boxerDash-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "punchSwing": {
      "files": [
        "punchSwing.wav",
        "punchSwing-2.wav",
        "punchSwing-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "punch": {
      "files": [
        "punch.wav",
        "punch-2.wav",
        "punch-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "palmPush": {
      "files": [
        "palmPush.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "dragonPull": {
      "files": [
        "dragonPull.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "meridianLock": {
      "files": [
        "meridianLock.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "channelStart": {
      "files": [
        "channelStart.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "channelTick": {
      "files": [
        "channelTick.wav",
        "channelTick-2.wav",
        "channelTick-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 3,
      "cooldown": 0.012,
      "priority": 1
    },
    "channelFinish": {
      "files": [
        "channelFinish.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 2
    },
    "breathing": {
      "files": [
        "breathing.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "dragonCharge": {
      "files": [
        "dragonCharge.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "dragonBurst": {
      "files": [
        "dragonBurst.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 2
    },
    "hitLight": {
      "files": [
        "hitLight.wav",
        "hitLight-2.wav",
        "hitLight-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "hitHeavy": {
      "files": [
        "hitHeavy.wav",
        "hitHeavy-2.wav",
        "hitHeavy-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "critAccent": {
      "files": [
        "critAccent.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "launcher": {
      "files": [
        "launcher.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "enemyShot": {
      "files": [
        "enemyShot.wav",
        "enemyShot-2.wav",
        "enemyShot-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "enemyTelegraph": {
      "files": [
        "enemyTelegraph.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 2
    },
    "teleport": {
      "files": [
        "teleport.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 2
    },
    "enemyCleave": {
      "files": [
        "enemyCleave.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "fieldOmen": {
      "files": [
        "fieldOmen.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "tileBurst": {
      "files": [
        "tileBurst.wav",
        "tileBurst-2.wav",
        "tileBurst-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 2,
      "cooldown": 0.045,
      "priority": 1
    },
    "waveSweep": {
      "files": [
        "waveSweep.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "dartVolley": {
      "files": [
        "dartVolley.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "counterBurst": {
      "files": [
        "counterBurst.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "playerHurt": {
      "files": [
        "playerHurt.wav",
        "playerHurt-2.wav",
        "playerHurt-3.wav"
      ],
      "gain": 0.92,
      "vary": 0.028,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "shieldBlock": {
      "files": [
        "shieldBlock.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 1
    },
    "drawCard": {
      "files": [
        "drawCard.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.045,
      "priority": 0
    },
    "aimOn": {
      "files": [
        "aimOn.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.045,
      "priority": 0
    },
    "aimOff": {
      "files": [
        "aimOff.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.045,
      "priority": 0
    },
    "pause": {
      "files": [
        "pause.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.045,
      "priority": 0
    },
    "victory": {
      "files": [
        "victory.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 2
    },
    "defeat": {
      "files": [
        "defeat.wav"
      ],
      "gain": 0.92,
      "vary": 0,
      "limit": 4,
      "cooldown": 0.012,
      "priority": 2
    }
  }
};
  if (typeof module === 'object' && module.exports) module.exports = manifest;
  else root.COMBAT_SOUND_MANIFEST = manifest;
})(globalThis);
